#!/usr/bin/env ruby

require 'rubygems'
require 'nokogiri'
require 'open-uri'

def get_row_content(row)
    row.xpath('td|th').map {|data| data.content}
end

def get_table_content(table)
    table.xpath('tr').map {|row| get_row_content(row)}
end

def load_page(command, argument)
    base_url = 'https://xenbuilder.uk.xensource.com/builds?'
    url = ""

    case command
    when "branch"
        url = "#{base_url}q_view=summary&q_product=carbon&q_branch=#{argument}"
    when "build"
        url = "#{base_url}q_view=details&q_product=carbon&q_number=#{argument}"
    else
        puts "Unknown command: #{command}"
        exit 1
    end

    Nokogiri.HTML(open(url))
end

def get_column_widths(table_content)
    column_widths = []

    # Iterate along the first row.
    table_content[0].each_with_index do |data, index|
        # Find the width of the longest item in this column.
        max_width = table_content.inject(0) do |result, row|
            data_length = row[index].nil? ? 0 : row[index].length
            [result, data_length].max
        end
        column_widths [index] = max_width
    end

    column_widths
end

def print_table(table_content)
    column_widths = get_column_widths(table_content)

    table_content.each do |row|
        row_string = '|'
        row.each_with_index do |data, index|
            row_string << ("%#{column_widths[index]}s" % data)
            row_string << '|'
        end
        puts row_string
    end
end

def run(command, argument)
    doc = load_page command, argument
    table = doc.xpath('//table[@class = "buildtable"]')
    table_content = get_table_content table
    print_table(table_content)
end

def usage()
    puts 'Usage: xenbuilder-scraper <command> <arg>'
end

if ARGV.length != 2
    usage
    exit 1
else
    run ARGV[0], ARGV[1]
end
